package com.astrazeneca.training.makerchecker.common;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.io.PrintWriter;
import java.io.StringWriter;

@Getter
@Setter
@AllArgsConstructor
@ToString
/*
 Read for the response formats : https://labs.omniti.com/labs/jsend
 */
public class JSendResponse {

    public static final String STATUS_SUCCESS ="success";
    public static final String STATUS_FAIL ="fail";
    public static final String STATUS_ERROR ="error";

    private String status;

    /*
    The data is used for returning the success data and fail validation errors
     */
    private Object data;

    /*
    It is used only when the status is error that is exception thrown.
     */
    private String message;

    /**
     * <p>Gets the stack trace from a Throwable as a String.</p>
     *
     *
     * @param throwable  the <code>Throwable</code> to be examined
     * @return the stack trace as generated by the exception's
     *  <code>printStackTrace(PrintWriter)</code> method
     */
    public static String getStackTrace(final Throwable throwable) {
        final StringWriter sw = new StringWriter();
        final PrintWriter pw = new PrintWriter(sw, true);
        throwable.printStackTrace(pw);
        return sw.getBuffer().toString();
    }

}
